name: Scrape Risk Leaderboard

on:
  schedule:
    - cron: "0 * * * *"   
  workflow_dispatch:       

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium undetected-chromedriver

      - name: Run scraper
        run: python scraper.py

      - name: Commit updated CSV
        run: |
          git config --global user.name "Scraper Bot"
          git config --global user.email "bot@example.com"
          git add frontend/public/leaderboard.csv
          git commit -m "Update leaderboard.csv [skip ci]" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/nrzdhmz/Scraping_RiskLeaderboard.git HEAD:main

